project_id = "uqnxdjehsgewuzjcwien"

[functions.get-daily-nutrition]
verify_jwt = false

[functions.lookup-barcode]
verify_jwt = false

[functions.export-user-data]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = false

[functions.admin-send-notification]
verify_jwt = false

[functions.admin-manage-products]
verify_jwt = false
